apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-app-postgres-data
  namespace: sample-app
spec:
  storageClassName: sample-app-db-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
